CREATE TABLE product (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	price INT UNSIGNED NOT NULL,
	registred_date DATETIME NOT NULL,
	slug VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE category (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	slug VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE product_category (
	product_id INT UNSIGNED NOT NULL,
	category_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (product_id, category_id),
	CONSTRAINT fk_product 
	FOREIGN KEY (product_id)
	REFERENCES product(id)
	ON DELETE CASCADE
	ON UPDATE RESTRICT,
	CONSTRAINT fk_category 
	FOREIGN KEY (category_id)
	REFERENCES category(id)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
);

CREATE TABLE user (
	username VARCHAR(255) NOT NULL,
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
)
